# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    product_manager:
        class: ApiBundle\Manager\ProductManager
        arguments: ["@doctrine.orm.entity_manager"]
    cart_manager:
        class: ApiBundle\Manager\CartManager
        arguments: ["@doctrine.orm.entity_manager"]
